# Generated by Django 5.0.6 on 2025-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña'),
        ),
    ]
