# Generated by Django 5.0.6 on 2025-05-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_company_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['denomination'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pdf_size',
            field=models.CharField(choices=[('T', 'Ticket'), ('A', 'A4')], default='T', max_length=10, verbose_name='Tamaño PDF'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'is_active'], name='users_user_company_d7ce30_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dni'], name='users_user_dni_287748_idx'),
        ),
    ]
