# Generated by Django 5.0.6 on 2025-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SALIDA')], default='NA', max_length=1, verbose_name='TIPO DE OPERACION')),
                ('operation_status', models.CharField(choices=[('1', 'REGISTRADO'), ('2', 'EMITIDO'), ('3', 'PENDIENTE DE BAJA'), ('4', 'EN PROCESO DE BAJA'), ('5', 'DADO DE BAJA'), ('6', 'RECHAZADO')], default='1', max_length=1, verbose_name='ESTADO')),
                ('serial', models.CharField(blank=True, max_length=4, null=True, verbose_name='SERIE')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='NUMERO')),
                ('currency', models.CharField(choices=[('PEN', 'SOLES'), ('USD', 'DÓLARES')], default='PEN', max_length=3, verbose_name='MONEDA')),
                ('sell_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='VALOR CAMBIO VENTA')),
                ('buy_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='VALOR CAMBIO COMPRA')),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('emit_date', models.DateField(blank=True, null=True)),
                ('emit_time', models.TimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('low_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items_total_discount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='DESCUENTO POR ITEM')),
                ('global_discount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='DESCUENTO GLOBAL')),
                ('global_discount_percent', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='PORCENTAJE DESCUENTO GLOBAL')),
                ('total_discount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL DESCUENTO')),
                ('igv_percent', models.DecimalField(decimal_places=6, default=18, max_digits=15, verbose_name='PORCENTAJE IGV')),
                ('igv_amount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL IGV')),
                ('total_taxable', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL GRAVADA')),
                ('total_unaffected', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL INAFECTA')),
                ('total_exempt', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL EXONERADA')),
                ('total_free', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL GRATUITA')),
                ('total_amount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOTAL IMPORTE')),
                ('send_person', models.BooleanField(default=False)),
                ('sunat_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='DESCRIPCION SUNAT')),
                ('sunat_description_low', models.CharField(blank=True, max_length=300, null=True, verbose_name='DESCRIPCION SUNAT BAJA')),
                ('sunat_status', models.BooleanField(default=False)),
                ('link_xml', models.CharField(blank=True, max_length=900, null=True, verbose_name='ENLACE XML')),
                ('link_cdr', models.CharField(blank=True, max_length=900, null=True, verbose_name='ENLACE CDR')),
                ('low_number', models.IntegerField(blank=True, null=True, verbose_name='NUMERO ANULACION')),
                ('summary_number', models.IntegerField(blank=True, null=True, verbose_name='NUMERO RESUMEN')),
                ('low_ticket', models.CharField(blank=True, max_length=100, null=True, verbose_name='TICKET ANULACION')),
                ('link_xml_low', models.CharField(blank=True, max_length=900, null=True, verbose_name='ENLACE XML DE BAJA')),
                ('link_cdr_low', models.CharField(blank=True, max_length=900, null=True, verbose_name='ENLACE CDR DE BAJA')),
                ('code_hash', models.CharField(blank=True, max_length=900, null=True, verbose_name='CODIGO HASH')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor unitario')),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Precio unitario')),
                ('discount_percentage', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Porcentaje de descuento')),
                ('total_discount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Descuento total')),
                ('total_value', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor total')),
                ('total_igv', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Igv total')),
                ('total_amount', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Importe total')),
                ('remaining_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle operacion',
                'verbose_name_plural': 'Detalles operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC')], default='1', max_length=2)),
                ('document', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
    ]
