# Generated by Django 5.0.6 on 2025-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('C', 'CAJA'), ('B', 'BANCO')], default='C', max_length=2)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('way_pay', models.IntegerField(choices=[(1, 'EFECTIVO [CONTADO]'), (2, 'POR PAGAR [CRÉDITO]')], default=1)),
                ('bank_operation_code', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
